### PR TITLE
Fix flathub linter errors/warnings

### PR DESCRIPTION
**Pull request by Erick555**
Closes #148

### CODE REVIEW

**Comment by Erick555** [comment]
This needs to wait until [anitya](https://release-monitoring.org/project/6141/) knows about 6.7.1.

**Comment by ghisvail** [comment]
bot, build

**Comment by Erick555** [comment]
The 6.7.1 tag is still not available at https://release-monitoring.org/project/6141/ so it won't work.

**Comment by Erick555** [comment]
@ghisvail now it's ready :smile:

**Comment by ghisvail** [comment]
Thanks for taking care of it

**Pull request merged**
