### PR TITLE
Improve calibre permissions

### PR DESCRIPTION
**Pull request by Erick555**
This is borrowed from https://github.com/flathub/com.calibre_ebook.calibre/pull/53 and reflects changes made in calibre 5.6.

### CODE REVIEW

**Comment by ntninja** [comment]
I was skeptical at first, but after some testing it appears as though `--filesystem=xdg-run/speech-dispatcher:ro` does prevent the app from assuming the role of the speech-dispatcher daemon while still allowing it to connect to a running instance. Ideally, it would be `--filesystem=xdg-run/speech-dispatcher:create,ro`, or similar, so that it also can connect if speech-dispatcher is started after the app but such a thing does not exist.

One thing I'm curious about: What is the benefit of sharing `--filesystem=xdg-run/speech-dispatcher:ro`, rather than just `--filesystem=xdg-run/speech-dispatcher/speechd.sock:ro`?

**Comment by Erick555** [comment]
It's just looking better. On second thought if this path can contain something else than socket I would go back to `--filesystem=xdg-run/speech-dispatcher/speechd.sock:ro`.

**Comment by ntninja** [comment]
It also contains log and PID files, but they don't appear to contain anything important. Some experimentation with `speech-dispatcher` reveals that it will automatically shut down when no client are connected and hence will create a new socket on next startup (as I've learned while investigation your claims socket nodes need be removed before the given socket address can be claimed again). At that point Calibre won't be able to connect anymore, since it won't have access to the new socket node.

Based on this I think we should stick to your choice. Lack of auto-spawning of speech-dispatcher from the Flatpak environment is going to make this a sub-optimal experience in any case, sadly.

**Comment by Erick555** [comment]
If the new socket has exact same name as the old one (I don't see they're numbered?) then what's the problem here?

> as I've learned while investigation your claims socket nodes need be removed before the given socket address can be claimed again

where did I claimed such thing?

> Lack of auto-spawning of speech-dispatcher from the Flatpak environment is going to make this a sub-optimal experience in any case, sadly.

I think the same is true for every single socket so this is nothing new.

**Comment by ntninja** [comment]
> If the new socket has exact same name as the old one (I don't see they're numbered?) then what's the problem here?

The problem is that to `bind(2)` to a Unix socket address/path, the path at which the socket node will be placed in the filesystem may not already exist apparently – and that is even true, if the existing filesystem node at that path is already an unbound socket node. In other words, once speech-dispatcher closes its Unix socket (during its shutdown), that socket node *must be deleted*/`unlink(2)`'d before any application will ever be able to bind a new socket to that path.

However when we add a Flatpak filesystem permission for `${XDG_RUNTIME_DIR}/speech-dispatcher/speechd.sock`, Flatpak will create a bind-mount for that path during sandbox creation and is makes only that exact *inode* available to Calibre. If that socket filesystem node is later deleted and recreated, this will result in a new inode being created at that path outside of the sandbox, but Calibre will not be able to see it as it only has access to the old now-unbound socket node from within the sandbox.
If we instead add permissions for accessing `${XDG_RUNTIME_DIR}/speech-dispatcher`, that directory's inode will be bound into the sandbox instead and since directories are mutable all changes within that directory (like recreating the socket node) will remain visible to Calibre even after setting up the sandbox. 

> > as I've learned while investigation your claims socket nodes need be removed before the given socket address can be claimed again
> 
> where did I claimed such thing?

The sentence was meant as *while investigating your claims, I learned that …*. I did not intend to make it sound like you claimed what is said in the latter part of the sentence. :slightly_smiling_face: 

The claim was supposed to be this from #66 (emphasis added):

> Note that I enhanced speech perm to --filesystem=xdg-run/speech-dispatcher:ro **which is more secure and cleaner.**

> > Lack of auto-spawning of speech-dispatcher from the Flatpak environment is going to make this a sub-optimal experience in any case, sadly.
> 
> I think the same is true for every single socket so this is nothing new.

No, its sadly a lot worse since:

  1. speech-dispatcher auto-terminates when there are no client connected
  2. Unlike, other sockets like Wayland, X11 or PulseAudio, speech-dispatcher is not an integral part of most desktop setups (unless you use a screenreader), so for most people Calibre will be the *only* thing trying to access it at the given moment
  3. There is no socket auto-activation for speech-dispatcher like there is for, say, Xwayland on otherwise Wayland-only user sessions

Really, given the above, this means that most people will have to manually launch
`speech-dispatcher -s -t0` to get any TTS from Calibre Flatpak. :slightly_frowning_face:

**Comment by ghisvail** [comment]
Thank you all for taking care of this

**Pull request merged**
