### PR TITLE
Update calibre to 3.32.0

### PR DESCRIPTION
**Pull request by sat3ll**

### CODE REVIEW

**Comment by ghisvail** [comment]
Don't forget to update the [release field](https://github.com/flathub/com.calibre_ebook.calibre/blob/64c3dccb8f398c6cb1eff980eca9b40c8cb8fe92/com.calibre_ebook.calibre.appdata.xml#L26) of the AppStream metadata, please. Thanks.

**Comment by sat3ll** [comment]
Done.

**Comment by ghisvail** [comment]
bot, build

**Comment by ghisvail** [comment]
Thank you for your contribution.

**Pull request merged**
