### PR TITLE
[TEST] Try building from source

### PR DESCRIPTION
**Pull request by tinywrkb**
This is very initial work to build from source. Right now, just testing that this builds on the CI.

### CODE REVIEW

**Comment by tinywrkb** [comment]
Success! Builds correctly for all architectures.  
This needs more works, so closing for now.

**Comment by tinywrkb** [comment]
@Erick555 thanks, I skimmed through the relevant bug report before I started working on this.

I'm following distro packaging, in the specific the Arch Linux package. The maintainer of the Arch Linux Calibre package has been a contributor to the project, and a major force behind the Python3 port. If nothing is broken there, then I find it hard to believe that we can't ship a fully functioning source build.  
The argument about a possible breakage because of some internal Qt API changes sounds to me like an excuse, especially when Flathub is lagging at least one Qt release behind distros. Distros will hit a breakage first, and their maintainers will do all the hard work, as Flathub will always lag behind.

There's an argument to say about complexity and build time, but in turn we get an aarch64 build, and much less wasted storage space, as we use the KDE runtime, and have PyQt base application dedup across multiple apps.  

I'm against putting this in the beta channel. This should go in or not.

Considering that auto-merging is enabled here, pushing updates to users with zero testing made, I approached this fully aware that it's likely that it won't be accepted.

I'll continue working on this until I believe it's ready, and then will send a new PR.

**Comment by ghisvail** [comment]
@Erick555 is right to point out that there has been an initial attempt at solving source builds, and that it is important to understand the factors and considerations as to why it has not been fruitful yet.

> The arguments against source build are:

> 1. Lack of upstream specific patches for dependencies

We could probably live with a number of Flatpak specific patches, as long as their respective complexity remained low. So far, both attempts introduced a non-trivial amount of modifications.

> 2. No upstream support for any bugs

That's my main source for concerns. A healthy upstream relationship is important, and I have yet to read a clear statement that packaging from source was welcome.

> 3. Vastly significant more effort to maintain flatpak

As a result of points 1 and 2.

**Comment by tinywrkb** [comment]
> Flathub Qt is updated quite fast these days.

No it's not. There's a separate KDE runtime for each minor Qt release. Should we worry about internal API changes in patch releases? I have no idea.

> Lack of upstream specific patches for dependencies

Fully functioning build here, at least after initial testing.
* Two patches for dependencies and one `CMakeList.txt`. I believe these exist in multiple distros.
* A patch with a very minor change to Calibre's generated sipbuild `pyproject.toml` files. And I haven't investigated yet upstreaming or if there are alternatives.

> ... and as I understand you plan to depend maintenance of flatpak on some distro package maintenance?

For sourcing patches for unmaintained libraries? Of course. When upstream is dead, or badly maintained, then it's pretty much common to see the same downstream patches used by multiple distros.  
For packaging the modules and maintenance? No.

**Comment by Erick555** [comment]
> Fully functioning build here, at least after initial testing.

I meant upstream maintains its own [patches](https://github.com/kovidgoyal/bypy/tree/master/patches) for various deps if it thinks it's relevant for calibre alongside versions that are currently supported. The exact set changes over time. It even maintains own buildystem for handling this. The https://github.com/flathub/com.calibre_ebook.calibre/pull/53 attempted for re-using it. I'm not concerned about downstream patches from various distributions.

> For packaging the modules and maintenance? No.

I had impression that if there is a bug or problem with build then you're going to wait until some distro fixes and reuse it.

**Comment by tinywrkb** [comment]
> I meant upstream maintains its own [patches](https://github.com/kovidgoyal/bypy/tree/master/patches) for various deps if it thinks it's relevant for calibre alongside versions that are currently supported.

As I said before, I'm following distro way of packaging. Each dependency is a separate Flatpak module (still, a single YAML manifest for the whole app).  
I have no plan to use Calibre's buildsystem to build dependencies. Using another half-baked buildsystem is just a bad idea, and I wish good-luck to whoever plan to maintain Flatpak packaging for that.

**Comment by Erick555** [comment]
I understand, yet this is what puts us at odds with upstream.

**Comment by tinywrkb** [comment]
If anyone wants to try, then look in my [source_build](https://github.com/tinywrkb/com.calibre_ebook.calibre/tree/source_build).  
And there's also a [source_build-qt6](https://github.com/tinywrkb/com.calibre_ebook.calibre/tree/source_build-qt6) with PyQt6, but currently it set with a different `app-id` to avoid surprises due to the major Qt version bump, like conversion of config and data stores.

**Pull request closed without merging**
