### PR TITLE
Update to 7.51. and fix appdata

### PR DESCRIPTION
**Pull request by Erick555**
Fixes https://github.com/flathub/com.calibre_ebook.calibre/pull/204

Fixes https://github.com/flathub/com.calibre_ebook.calibre/issues/203

### CODE REVIEW

**Comment by Erick555** [comment]
@ghisvail could you take a look?

**Comment by ghisvail** [comment]
I won't have time this week. I fully trust your judgement if you want to merge this asap.

**Comment by Erick555** [comment]
@ghisvail please merge it then (I can't)

**Comment by ghisvail** [comment]
Thanks @Erick555

**Comment by bbhtt** [comment]
@ghisvail build is failing, you have to fix the metainfo file https://buildbot.flathub.org/#/builders/6/builds/100897

**Comment by Erick555** [comment]
@bbhtt metainfo is created by upstream, I don't see how to workaround current failures (which look like cosmetic issue tbh).

**Comment by bbhtt** [comment]
Where is the file? I can patch it

**Comment by Erick555** [comment]
Upstream creates it [dynamically](https://github.com/kovidgoyal/calibre/tree/master/src/calibre) on release. I don't know if this problem wasn't introduced to fix [another](https://github.com/kovidgoyal/calibre/pull/1436) warning?

Flathub uses binary build so you need to download it and check the file `/app/share/metainfo/calibre-ebook-viewer.metainfo.xml` is original and `/app/appdata/com.calibre_ebook.calibre.appdata.xml` is what flathub uses after [modifications](https://github.com/flathub/com.calibre_ebook.calibre/blob/master/com.calibre_ebook.calibre.yaml#L71).

**Comment by bbhtt** [comment]
The actual description is fine, descriptions in release tag are adding a xml:lang=en which is problematic.

a) It should be in `<p>` tag
b) English tags must not have xml:lang

Both are documented in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#metainfo-translations

If the maintainers can open an issue for this, upstream, it'd be appreciated.

**Comment by Erick555** [comment]
@kovidgoyal do you think above is fixable on calibre side?

**Comment by kovidgoyal** [comment]
What's fixable? If you mean adding a developer_name, feel free to send a PR I will merge.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/calibre/commit/d10cdf8a86ce14f37d8acc5374aacd03e7267b3d

**Comment by bbhtt** [comment]
@kovidgoyal Please see my comment https://github.com/flathub/com.calibre_ebook.calibre/pull/205#issuecomment-1951340436

The release tags in appdata have xml:lang=en in description.

**Comment by kovidgoyal** [comment]
That was changed a while ago.

**Comment by Erick555** [comment]
@kovidgoyal `calibre-gui.metainfo.xml` in 7.51, created with `calibre_postinstall` still includes:

```
<releases>
     <release version="7.5.1" date="2024-02-09">
      <description xml:lang="en">
...
```
which is unfortunately invalid according to appstream spec

I attached it below: (you may remove `txt` from filename)
[calibre-gui.metainfo.xml.txt](https://github.com/flathub/com.calibre_ebook.calibre/files/14323595/calibre-gui.metainfo.xml.txt)

**Comment by Erick555** [comment]
This should be fixed by https://github.com/kovidgoyal/calibre/commit/32a4423efbeb940a9613ab75e2e807e27f0aeb1a

We need to wait for next release.

**Pull request merged**
