### PR TITLE
bump runtime to 24.08

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by Erick555** [comment]
try updating links to [2.30](http://links.twibright.com/download/links-2.30.tar.bz2) sha256 is `c4631c6b5a11527cdc3cb7872fc23b7f2b25c2b021d596be410dadb40315f166`

**Comment by ghisvail** [comment]
Errors reported from the build:

```
checking whether the C compiler (gcc -O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ) works... no
configure: error: installation or configuration problem: C compiler cannot create executables.
FB: host_command_exited_cb 2814323 256
]2;flatpak-builder: Cleanup linksError: module links: Child process exited with code 1
```

**Comment by muelli** [comment]
yeah, that's pretty strange.
maybe a flake.
let's wait for a day or so.

**Comment by Erick555** [comment]
I told you what to [try](https://github.com/flathub/com.calibre_ebook.calibre/pull/232#issuecomment-2409090870). It won't fix themselves.

**Comment by Erick555** [comment]
links is fixed now you may try updating [xmlto](https://pagure.io/xmlto/archive/0.0.29/xmlto-0.0.29.tar.bz2) to 0.0.29 sha256 is `6000d8e8f0f9040426c4f85d7ad86789bc88d4aeaef585c4d4110adb0b214f21`

**Pull request merged**
